import { ArrowLeft, CalendarDays, CreditCard, UploadCloud } from 'lucide-react'
import { type ChangeEvent, useEffect, useState } from 'react'
import { Link, useParams } from 'react-router-dom'
import { getAccountBooking, uploadDepositReceipt, type AccountBookingDetail } from '../api/account'
import { resolveApiAssetUrl } from '../api/broker'
import { useAuth } from '../auth/AuthContext'
import { AppLayout } from '../components/AppLayout'

const money = new Intl.NumberFormat('az-AZ', { style: 'currency', currency: 'AZN' })
const dateTime = new Intl.DateTimeFormat('az-AZ', { dateStyle: 'medium', timeStyle: 'short' })
const labels: Record<string, string> = { requested: 'Qəbz gözlənilir', receipt_uploaded: 'Qəbz broker tərəfindən yoxlanılır', approved: 'Beh təsdiqlənib', rejected: 'Qəbz rədd edilib', expired: 'Son tarix keçib', cancelled: 'Ləğv edilib' }

export function AccountBookingDetailPage() {
  const { id } = useParams(); const bookingId = Number(id); const { session } = useAuth(); const [booking, setBooking] = useState<AccountBookingDetail>(); const [loading, setLoading] = useState(true); const [uploading, setUploading] = useState(false); const [error, setError] = useState(''); const [success, setSuccess] = useState('')
  const load = async () => { if (!session) return; setLoading(true); setError(''); try { setBooking(await getAccountBooking(bookingId, session.accessToken)) } catch (cause) { console.error('Account booking load failed', cause); setError(cause instanceof Error ? cause.message : 'Rezervasiya yüklənmədi.') } finally { setLoading(false) } }
  useEffect(() => { void load() }, [bookingId, session?.accessToken])
  const upload = async (event: ChangeEvent<HTMLInputElement>) => { const file = event.target.files?.[0]; if (!file || !session) return; setUploading(true); setError(''); setSuccess(''); try { await uploadDepositReceipt(bookingId, file, session.accessToken); setSuccess('Qəbz uğurla yükləndi və broker yoxlamasına göndərildi.'); await load() } catch (cause) { console.error('Receipt upload failed', cause); setError(cause instanceof Error ? cause.message : 'Qəbz yüklənmədi.') } finally { setUploading(false); event.target.value = '' } }
  return <AppLayout><section className="account-detail-page"><div className="container"><Link className="back-link" to="/account"><ArrowLeft size={16} /> Rezervasiyalarıma qayıt</Link>{loading ? <div className="broker-loading">Rezervasiya yüklənir…</div> : error && !booking ? <div className="broker-error">{error}</div> : booking && <><div className="broker-detail-heading"><div><span className="eyebrow">REZERVASİYA #{booking.bookingId}</span><h1>{booking.rentalHomeTitle}</h1><p>{booking.city}{booking.district ? ` · ${booking.district}` : ''}</p></div><strong>{money.format(booking.totalAmount)}</strong></div>{error && <div className="broker-error" role="alert">{error}</div>}{success && <div className="account-success">{success}</div>}<div className="account-detail-layout"><article><h2>Seçilmiş tarixlər</h2><div className="broker-date-chips">{booking.dates.map((value) => <span key={value}><CalendarDays /> {value}</span>)}</div><h2>Rezervasiya məlumatı</h2><p>{booking.guests} qonaq · gecəlik {money.format(booking.dailyPrice)}</p></article><article className="customer-deposit-card"><CreditCard /><h2>Beh məlumatları</h2>{!booking.deposit ? <p>Broker beh təlimatını göndərdikdə burada görünəcək. Hazırda ödəniş etməyin.</p> : <><em>{labels[booking.deposit.statusCode] ?? booking.deposit.statusCode}</em><div><span>Məbləğ</span><strong>{money.format(booking.deposit.amount)}</strong></div><div><span>Son tarix</span><strong>{booking.deposit.deadlineAt ? dateTime.format(new Date(booking.deposit.deadlineAt)) : '—'}</strong></div><div><span>Kart sahibi</span><strong>{booking.deposit.cardHolderName || '—'}</strong></div><div><span>Maskalanmış kart</span><strong>{booking.deposit.cardPanMasked || '—'}</strong></div><div><span>Bank</span><strong>{booking.deposit.bankName || '—'}</strong></div>{booking.deposit.note && <p>{booking.deposit.note}</p>}{booking.deposit.reviewNote && <p className="deposit-review-note">Broker qeydi: {booking.deposit.reviewNote}</p>}{booking.deposit.receipt && <a className="receipt-link" href={resolveApiAssetUrl(booking.deposit.receipt.fileUrl)} target="_blank" rel="noreferrer">Yüklənmiş qəbzi aç</a>}{(booking.deposit.statusCode === 'requested' || booking.deposit.statusCode === 'rejected' && booking.deposit.allowReupload) && <label className="receipt-upload button button-primary"><UploadCloud size={17} /> {uploading ? 'Yüklənir…' : 'Qəbz şəkli yüklə'}<input type="file" accept="image/jpeg,image/png,image/webp" disabled={uploading} onChange={(event) => void upload(event)} /></label>}</>}</article></div></>}</div></section></AppLayout>
}
